using AutoMapper;
using ECommerce.Application.Common;
using ECommerce.Application.Contracts;
using ECommerce.Application.DTOs.BasketDTOs;
using ECommerce.Application.Specification;
using ECommerce.Domain.Contracts;
using ECommerce.Domain.Entities.Orders;
using ECommerce.Domain.Entities.Products;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static System.Formats.Asn1.AsnWriter;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Error = ECommerce.Application.Common.Error;

namespace ECommerce.Application.Services
{
    public class PaymentService : IPaymentService
    {
        private readonly IBasketRepository _basketRepository;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IPaymentGateway _paymentGateway;
        private readonly PaymentGatewaySettings _paymentGatewaySettings;
        private readonly IMapper _mapper;

        public PaymentService(IBasketRepository basketRepository ,IUnitOfWork unitOfWork , IPaymentGateway paymentGateway , IOptions<PaymentGatewaySettings> options, IMapper mapper) 
        {
            _basketRepository = basketRepository;
            _unitOfWork = unitOfWork;
            _paymentGateway = paymentGateway;
            _paymentGatewaySettings = options.Value;
            _mapper = mapper;
        }

        public async Task<Result<BasketDto>> CreateOrUpdatePaymentIntent(string basketId, CancellationToken ct = default) //  create basket then this CreateOrUpdatePaymentIntent  gives basket clientsec and intentt then order => listen with web hock  on clinetsec and intent done pay with deleted basket  paymentstatus on order succ       
        {
            //Create Or Update payment => connection stripe so will did this in infrastructure to kill the Tight Coupling and achieve Loose Coupling
            //clientsecrent   paymentintentid
            //1) Get basket [validate]
            var basket = await _basketRepository.GetBasketAsync(basketId,ct);
            if (basket == null)
                return Result<BasketDto>.Fail(Error.NotFound(Description: "Basket Not Found"));
            if(basket.Items.Count ==0)
                return Result<BasketDto>.Fail(Error.Validation(Description: "Basket Empty"));

            //2) get deliverymethod
            if (!basket.DeliveryMethodId.HasValue)
            {
                return Result<BasketDto>.Fail(Error.Validation(Description: "No DeliveryMethod"));
            }
            var deliverymethod = await _unitOfWork.GetRepository<DeliveryMethod, int>().GetByIdAsync(basket.DeliveryMethodId.Value,ct); 
            if(deliverymethod == null)
                return Result<BasketDto>.Fail(Error.NotFound(Description: "DeliveryMethod Not Found"));
            //cost

            basket.ShippingPrice = deliverymethod.Price;
            //3) product prices

            var productIds = basket.Items.Select(X => X.Id).ToHashSet();
            var products = (await _unitOfWork.GetRepository<Product, int>().GetAllAsync(new ProductWithIdSpecification(productIds), ct)).ToDictionary(X => X.Id);
            foreach (var item in basket.Items)
            {
                if(!products.TryGetValue(item.Id ,out var product))
                    return Result<BasketDto>.Fail(Error.NotFound(Description: "Product Not Found"));
                item.Price = product.Price;
            }
            //Total amount
            var subtotal = basket.Items.Sum(X => X.Price * X.Quantity);
            var amount = (long) ((subtotal + basket.ShippingPrice)*100m);


            //5 paymentintentid => empty => create
            if (string.IsNullOrEmpty(basket.PaymentIntentId))
            {
                //create 
                var result = await _paymentGateway.CreatePaymentIntentAsync(amount,_paymentGatewaySettings.DefaultCurrency , ct);
                basket.PaymentIntentId = result.PaymentIntentId;
                basket.ClientSecret = result.ClientSecret;
            }
            else
            {
                //update
                 await _paymentGateway.UpdatePaymentIntentAsync(basket.PaymentIntentId, amount, ct);

            }
            await _basketRepository.CreateOrUpdateBasketAsync(basket, ct :ct);

            return Result<BasketDto>.OK(_mapper.Map<BasketDto>(basket));
        }
    }
    //SecretKey → Used only by the backend to authenticate and communicate with the Stripe API.It must never be exposed to the frontend.
    //PaymentIntentId → The unique identifier of the Stripe PaymentIntent.It is typically stored in the Basket and later in the Order to track the payment.
    //ClientSecret → Generated by Stripe along with the PaymentIntent.It is returned to the frontend, where the Stripe SDK uses it to securely confirm the payment.
}


#region Cycle
        //1.Create Basket
        //        ↓
        //2. Add/Update Basket Items
        //        ↓
        //3. Select Delivery Method
        //        ↓
        //4. Create/Update PaymentIntent
        //        ↓
        //Stripe returns:
        //-PaymentIntentId
        //- ClientSecret
        //        ↓
        //Store both in the Basket
        //        ↓
        //5. Frontend confirms the payment using ClientSecret
        //        ↓
        //Stripe processes the payment
        //        ↓
        //6. Stripe sends a Webhook to your backend
        //        ↓
        //7. Backend updates the Order PaymentStatus
        //order
        //Basket
        //   ↓
        //Create PaymentIntent
        //   ↓
        //Create Order (Status = Pending)
        //   ↓
        //Frontend confirms payment
        //   ↓
        //Webhook
        //   ↓
        //Update Order -> PaymentReceived
        
#endregion